In [2]:
from qutip import *

In [3]:
import numpy as np

import matplotlib.pyplot as plt

# The quantum object class

In [4]:
print(Qobj())

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]


In [5]:
print(Qobj([[1],[2],[3],[4],[5]]))

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [6]:
x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


In [7]:
r = np.random.rand(8, 8)
print(Qobj(r))

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.33060943 0.29314151 0.82170027 0.42846551 0.89378736 0.90783233
  0.86797898 0.7865101 ]
 [0.40266153 0.44844116 0.88152248 0.07202133 0.69032239 0.1317123
  0.00657011 0.29070351]
 [0.15203079 0.29815243 0.48924943 0.3247457  0.7385379  0.38105489
  0.18853758 0.62568671]
 [0.13074871 0.13614371 0.59514342 0.73943296 0.60814968 0.29698553
  0.6364438  0.97327015]
 [0.20627127 0.71100769 0.77748009 0.39616791 0.9968155  0.49075439
  0.39633722 0.59960551]
 [0.68566915 0.16458442 0.47068571 0.12044367 0.5080246  0.72525153
  0.34255587 0.41283155]
 [0.72821582 0.97998897 0.07800379 0.91177562 0.96193116 0.89357617
  0.0036448  0.15245709]
 [0.24738966 0.64213157 0.71891002 0.62471028 0.10473884 0.93714279
  0.07291763 0.9389534 ]]


# States and operators

In [10]:
basis(7,5)

Quantum object: dims = [[7], [1]], shape = (7, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [11]:
coherent(10,0.7-0.5j)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[ 6.90734331e-01+0.00000000e+00j]
 [ 4.83514031e-01-3.45367165e-01j]
 [ 1.17221503e-01-3.41896050e-01j]
 [-5.13223820e-02-1.72014577e-01j]
 [-6.09664760e-02-4.73745049e-02j]
 [-2.96788082e-02-1.19804826e-03j]
 [-8.72585340e-03+5.71570993e-03j]
 [-1.22879820e-03+3.16209470e-03j]
 [ 2.53718214e-04+9.95272979e-04j]
 [ 2.41463105e-04+2.03769850e-04j]]

# Qobj attributes

In [12]:
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [13]:
 sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [14]:
jmat(5/2.0,'+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

# Qobj Math

In [17]:
q = destroy(4)
q.dims

[[4], [4]]

In [18]:
q.shape

(4, 4)

In [19]:
q.type

'oper'

In [20]:
q.isherm

False

In [21]:
q.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

In [23]:
q = destroy(4)
x = sigmax()
q + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

In [24]:
x * x

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [25]:
q ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

In [26]:
 x / np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

# Functions operating on Qobj class

In [28]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [29]:
basis(5, 3).dag()

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 0. 0. 1. 0.]]

In [30]:
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [31]:
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

In [32]:
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

In [33]:
coherent_dm(5, 1).norm()

1.000000021054981

In [34]:
coherent_dm(5, 1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

In [35]:
coherent_dm(5, 1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

In [36]:
coherent_dm(5, 1).tr()

0.9999999999999999

In [37]:
(basis(4, 2) + basis(4, 1)).unit()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]